# Generated by Django 3.1.2 on 2020-10-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '연습보드 게시판', 'verbose_name_plural': '연습보드 게시판'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='practice_board',
        ),
    ]
