# Generated by Django 3.1.2 on 2020-10-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='None', max_length=128, verbose_name='구매자주소'),
        ),
    ]
