# Generated by Django 3.1.2 on 2020-10-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201028_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default='0', verbose_name='상품가격'),
        ),
        migrations.AddField(
            model_name='order',
            name='productimg',
            field=models.CharField(default='None', max_length=64, verbose_name='상품이미지'),
        ),
    ]
