# Generated by Django 3.1.2 on 2020-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countprice',
            field=models.IntegerField(default='0', verbose_name='상품가격'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default='0', verbose_name='총가격'),
        ),
    ]
