# Generated by Django 3.1.2 on 2020-10-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20201026_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('product', models.ImageField(blank=True, default='None', upload_to='images', verbose_name='상품이미지')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('reguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='등록자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'pactice_product',
            },
        ),
    ]
