# Generated by Django 3.1.2 on 2020-10-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32, verbose_name='아이디')),
                ('username', models.CharField(max_length=32, verbose_name='이름')),
                ('password', models.CharField(max_length=32, verbose_name='비밀번호')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
