# Generated by Django 3.1.2 on 2020-10-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '연습보드 사용자', 'verbose_name_plural': '연습보드 사용자'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='practice_user',
        ),
    ]
