# Generated by Django 3.1.2 on 2020-10-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='None', max_length=64, verbose_name='이메일'),
        ),
    ]
