# Generated by Django 3.1.2 on 2020-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userimg',
            field=models.ImageField(blank=True, default='None', upload_to='images', verbose_name='유저이미지'),
        ),
    ]
